# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171018_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('PA', 'Patient'), ('DO', 'Doctor'), ('PH', 'Pharmacist'), ('NA', 'Not Applicable')], default='PA', max_length=2, verbose_name='user type'),
        ),
    ]
